// Proizvodi: javna Entext ponuda. Cijene, jedinice i pokrivenost pakovanja: DEMO.
window.ENTEXT_PRODUCTS = [
  {
    "id": "1",
    "sku": "ENT-001",
    "sourceSku": "",
    "name": "Focus 70 česma za lavabo",
    "category": "Kupatilo",
    "brand": "HANSGROHE",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/HANSGROHE_Focus_70_hrom-1.png",
    "image": "assets/products/ent-001.png",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 135,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "Focus 70",
      "Završna obrada": "Hrom"
    },
    "description": "Focus 70 • Hrom",
    "fallback": "assets/products/fallback-kupatilo.svg"
  },
  {
    "id": "2",
    "sku": "ENT-002",
    "sourceSku": "",
    "name": "APZ30-650M tuš kanalica",
    "category": "Vodovod i kanalizacija",
    "brand": "ALCA",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/ALCA_APZ30_650M-1-300x300.png",
    "image": "assets/products/ent-002.png",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 94,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "APZ30-650M",
      "Dužina": "650 mm"
    },
    "description": "APZ30-650M • 650 mm",
    "fallback": "assets/products/fallback-vodovod.svg"
  },
  {
    "id": "3",
    "sku": "ENT-003",
    "sourceSku": "",
    "name": "CE 40 fuga, siva, 2 kg",
    "category": "Građevinski program",
    "brand": "HENKEL / CERESIT",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/CERESIT_CE40_2kg-1-300x254.png",
    "image": "assets/products/ent-003.png",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 32,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CE 40",
      "Boja": "Siva",
      "Pakovanje": "2 kg"
    },
    "description": "CE 40 • Siva • 2 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "4",
    "sku": "ENT-004",
    "sourceSku": "",
    "name": "Design SP walk-in tuš panel, 90 × 190 cm",
    "category": "Kupatilo",
    "brand": "HÜPPE",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/HUPPE_Design_SP_90x190-1.jpg",
    "image": "assets/products/ent-004.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 360,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "Design SP",
      "Dimenzije": "90 × 190 cm",
      "Završna obrada": "Sjajna srebrna",
      "Obrada stakla": "Anti-Plaque"
    },
    "description": "Design SP • 90 × 190 cm • Sjajna srebrna • Anti-Plaque",
    "fallback": "assets/products/fallback-kupatilo.svg"
  },
  {
    "id": "5",
    "sku": "ENT-005",
    "sourceSku": "",
    "name": "AK 14 SIVI ljepilo za keramiku, 25 kg",
    "category": "Građevinski program",
    "brand": "ISOMAT",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/ISOMAT_AK14_sivi_25kg.png",
    "image": "assets/products/ent-005.png",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 10,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "AK 14 SIVI",
      "Pakovanje": "25 kg",
      "Klasa": "C1TE"
    },
    "description": "AK 14 SIVI • 25 kg • C1TE",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "6",
    "sku": "ENT-006",
    "sourceSku": "",
    "name": "COX česma za kadu sa tuš ručkom",
    "category": "Kupatilo",
    "brand": "PAINI",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/PAINI_COX_78CR100_800x800-1.png",
    "image": "assets/products/ent-006.png",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 210,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "COX",
      "Završna obrada": "Hrom",
      "Tip": "Česma za kadu sa tuš ručkom"
    },
    "description": "COX • Hrom • Česma za kadu sa tuš ručkom",
    "fallback": "assets/products/fallback-kupatilo.svg"
  },
  {
    "id": "7",
    "sku": "ENT-007",
    "sourceSku": "",
    "name": "S501.1 ugradni vodokotlić sa tipkom",
    "category": "Kupatilo",
    "brand": "ALCA",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/ALCA_S501_1_bijela_tipka.webp",
    "image": "assets/products/ent-007.webp",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 185,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "S501.1",
      "Ugradnja": "Suva gradnja",
      "Boja tipke": "Bijela"
    },
    "description": "S501.1 • Suva gradnja • Bijela",
    "fallback": "assets/products/fallback-kupatilo.svg"
  },
  {
    "id": "8",
    "sku": "ENT-008",
    "sourceSku": "",
    "name": "Selnova lavabo, 55 × 44 cm",
    "category": "Kupatilo",
    "brand": "GEBERIT",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/GEBERIT_Selnova_lavabo_55x44-1024x1024.jpg",
    "image": "assets/products/ent-008.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 140,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "Selnova",
      "Dimenzije": "55 × 44 cm",
      "Boja": "Bijela"
    },
    "description": "Selnova • 55 × 44 cm • Bijela",
    "fallback": "assets/products/fallback-kupatilo.svg"
  },
  {
    "id": "9",
    "sku": "ENT-009",
    "sourceSku": "",
    "name": "Selnova Rimfree T54 WC šolja",
    "category": "Kupatilo",
    "brand": "GEBERIT",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/GEBERIT_Selnova_Rimfree_T54_WC_set.jpg",
    "image": "assets/products/ent-009.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 135,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "Selnova Rimfree T54",
      "Dimenzije": "53 × 39 × 36 cm",
      "Daska": "Soft-close"
    },
    "description": "Selnova Rimfree T54 • 53 × 39 × 36 cm • Soft-close",
    "fallback": "assets/products/fallback-kupatilo.svg"
  },
  {
    "id": "10",
    "sku": "ENT-010",
    "sourceSku": "",
    "name": "ATRIUM RIMINI RLV blanco zidna pločica",
    "category": "Keramika",
    "brand": "PAMESA CERAMICA",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/Pamesa_ATRIUM_RIMINI_RLV_blanco_33_3x55-1024x619.jpg",
    "image": "assets/products/ent-010.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 28,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 0.7326,
    "attributes": {
      "Dimenzije": "33,3 × 55 cm",
      "Završna obrada": "Glossy",
      "Namjena": "Zidna pločica"
    },
    "description": "33,3 × 55 cm • Glossy • Zidna pločica",
    "fallback": "assets/products/fallback-keramika.svg"
  },
  {
    "id": "11",
    "sku": "ENT-011",
    "sourceSku": "",
    "name": "ATRIUM VIGGO roble podna pločica",
    "category": "Keramika",
    "brand": "PAMESA CERAMICA",
    "source": "https://entext.me/entext-kupatilo-za-1-000-e/",
    "remoteImage": "https://entext.me/wp-content/uploads/2026/09/Pamesa_ATRIUM_VIGGO_roble_20x75-1024x283.jpg",
    "image": "assets/products/ent-011.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 64,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 0.6,
    "attributes": {
      "Dimenzije": "20 × 75 cm",
      "Završna obrada": "Mat",
      "Namjena": "Podna pločica"
    },
    "description": "20 × 75 cm • Mat • Podna pločica",
    "fallback": "assets/products/fallback-keramika.svg"
  },
  {
    "id": "12",
    "sku": "ENT-012",
    "sourceSku": "695082",
    "name": "HAMPTON brown plocica 14,3×90 (A)",
    "category": "Keramika",
    "brand": "PORCELANOSA S.A.",
    "source": "https://entext.me/product/hampton-brown-plocica-143x90-a/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/695082.jpg",
    "image": "assets/products/ent-012.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 41,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 0.5148,
    "attributes": {
      "Dimenzije": "14,3 × 90 cm",
      "Boja": "Brown",
      "Entext šifra": "695082"
    },
    "description": "14,3 × 90 cm · Brown",
    "fallback": "assets/products/fallback-keramika.svg"
  },
  {
    "id": "13",
    "sku": "ENT-013",
    "sourceSku": "920059",
    "name": "EVOSTONE ivory plocica 60×119,5cm, nat, ret",
    "category": "Keramika",
    "brand": "UNICOM srl",
    "source": "https://entext.me/product/evostone-ivory-plocica-60x1195cm-nat-ret/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/920059.jpg",
    "image": "assets/products/ent-013.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 34,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.868,
    "attributes": {
      "Dimenzije": "60 × 119,5 cm",
      "Boja": "Ivory",
      "Završna obrada": "Nat",
      "Ivica": "Ret",
      "Entext šifra": "920059"
    },
    "description": "60 × 119,5 cm · Ivory · Nat · Ret",
    "fallback": "assets/products/fallback-keramika.svg"
  },
  {
    "id": "23",
    "sku": "ENT-023",
    "sourceSku": "021034",
    "name": "ATRIUM ALPHA taupe plocica 25x70cm",
    "category": "Keramika",
    "brand": "PAMESA CERAMICA",
    "source": "https://entext.me/product/atrium-alpha-taupe-plocica-25x70/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/021034.jpg",
    "image": "assets/products/ent-023.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 46,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 0.7,
    "attributes": {
      "Dimenzije": "25 × 70 cm",
      "Boja": "Taupe",
      "Entext šifra": "021034"
    },
    "description": "25 × 70 cm • Taupe",
    "fallback": "assets/products/fallback-keramika.svg"
  },
  {
    "id": "24",
    "sku": "ENT-024",
    "sourceSku": "787014",
    "name": "BIANCHI dolce pločica 30x90cm,white matt",
    "category": "Keramika",
    "brand": "TAU CERAMICA SOLUTIONS s.l.u",
    "source": "https://entext.me/product/bianchi-dolce-plocica-30x90cmwhite-matt/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/787014.jpg",
    "image": "assets/products/ent-024.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 52,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 1.08,
    "attributes": {
      "Dimenzije": "30 × 90 cm",
      "Boja": "White",
      "Završna obrada": "Matt",
      "Entext šifra": "787014"
    },
    "description": "30 × 90 cm • White • Matt",
    "fallback": "assets/products/fallback-keramika.svg"
  },
  {
    "id": "25",
    "sku": "ENT-025",
    "sourceSku": "786201",
    "name": "EXALT OF CERIM magic with luc plocica 30x60cm ret,lucido",
    "category": "Keramika",
    "brand": "FLORIM CERAMICHE spa",
    "source": "https://entext.me/product/exalt-of-cerim-magic-with-luc-plocica-30x60cm-retlucido/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/786201.jpg",
    "image": "assets/products/ent-025.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 28,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 0.72,
    "attributes": {
      "Dimenzije": "30 × 60 cm",
      "Završna obrada": "Lucido",
      "Ivica": "Ret",
      "Entext šifra": "786201"
    },
    "description": "30 × 60 cm • Lucido • Ret",
    "fallback": "assets/products/fallback-keramika.svg"
  },
  {
    "id": "28",
    "sku": "ENT-028",
    "sourceSku": "294163",
    "name": "Tarkett laminat Navigator 1233 4V Bosphorus",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-navigator-1233-4v-bosphorus/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/294163.jpg",
    "image": "assets/products/ent-028.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 48,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Navigator",
      "Entext šifra": "294163"
    },
    "description": "Laminat • Navigator",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "29",
    "sku": "ENT-029",
    "sourceSku": "294164",
    "name": "Tarkett laminat Navigator 1233 4V La manche",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-navigator-1233-4v-la-manche/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/294164-300x300.jpg",
    "image": "assets/products/ent-029.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 56,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Navigator",
      "Entext šifra": "294164"
    },
    "description": "Laminat • Navigator",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "30",
    "sku": "ENT-030",
    "sourceSku": "297008",
    "name": "Tarkett laminat Navigator 1233 Spencer",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-navigator-1233-spencer/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/297008-300x300.jpg",
    "image": "assets/products/ent-030.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 42,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Navigator",
      "Entext šifra": "297008"
    },
    "description": "Laminat • Navigator",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "31",
    "sku": "ENT-031",
    "sourceSku": "294493",
    "name": "Tarkett laminat Gallery 1233 4V Monet",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-gallery-1233-4v-monet/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/294493-300x300.jpg",
    "image": "assets/products/ent-031.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 54,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Gallery",
      "Entext šifra": "294493"
    },
    "description": "Laminat • Gallery",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "32",
    "sku": "ENT-032",
    "sourceSku": "294165",
    "name": "Tarkett laminat Navigator 1233 4V Gibraltar",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-navigator-1233-4v-gibraltar/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/294165-300x300.jpg",
    "image": "assets/products/ent-032.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 48,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Navigator",
      "Entext šifra": "294165"
    },
    "description": "Laminat • Navigator",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "33",
    "sku": "ENT-033",
    "sourceSku": "294506",
    "name": "Tarkett laminat Gallery 1233 4V Greco",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-gallery-1233-4v-greco/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/294506-300x300.jpg",
    "image": "assets/products/ent-033.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 56,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Gallery",
      "Entext šifra": "294506"
    },
    "description": "Laminat • Gallery",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "34",
    "sku": "ENT-034",
    "sourceSku": "294508",
    "name": "Tarkett laminat Gallery 1233 4V Dali",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-gallery-1233-4v-dali/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/294508.jpg",
    "image": "assets/products/ent-034.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 42,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Gallery",
      "Entext šifra": "294508"
    },
    "description": "Laminat • Gallery",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "35",
    "sku": "ENT-035",
    "sourceSku": "294171",
    "name": "Tarkett laminat Navigator 1233 4V Marco Polo",
    "category": "Podovi",
    "brand": "TARKETT SEE d.o.o.",
    "source": "https://entext.me/product/tarkett-laminat-navigator-1233-4v-marco-polo/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/294171.jpg",
    "image": "assets/products/ent-035.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 54,
    "unit": "kutija",
    "pack": 1,
    "boxCoverage": 2.1,
    "attributes": {
      "Vrsta": "Laminat",
      "Serija": "Navigator",
      "Entext šifra": "294171"
    },
    "description": "Laminat • Navigator",
    "fallback": "assets/products/fallback-podovi.svg"
  },
  {
    "id": "36",
    "sku": "ENT-036",
    "sourceSku": "192123",
    "name": "CERESIT CM 11 lijepak za keramiku 5 kg",
    "category": "Građevinski program",
    "brand": "CERESIT",
    "source": "https://entext.me/product/ceresit-cm-11-lijepak-za-keramiku-5-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/192123.jpg",
    "image": "assets/products/ent-036.jpg",
    "imageKind": "photo",
    "photoNote": "Javna fotografija ovog modela može prikazivati drugo pakovanje; za količinu pogledajte naziv artikla.",
    "baseNet": 12,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CM 11",
      "Pakovanje": "5 kg",
      "Entext šifra": "192123"
    },
    "description": "CM 11 • 5 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "37",
    "sku": "ENT-037",
    "sourceSku": "192082",
    "name": "CERESIT CM 16 lijepak za keramiku 25 kg",
    "category": "Građevinski program",
    "brand": "CERESIT",
    "source": "https://entext.me/product/ceresit-cm-16-lijepak-za-keramiku-25-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/192082.jpg",
    "image": "assets/products/ent-037.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 24,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CM 16",
      "Pakovanje": "25 kg",
      "Entext šifra": "192082"
    },
    "description": "CM 16 • 25 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "38",
    "sku": "ENT-038",
    "sourceSku": "191098",
    "name": "CERESIT CM 17 lijepak za keramiku 25 kg",
    "category": "Građevinski program",
    "brand": "CERESIT",
    "source": "https://entext.me/product/ceresit-cm-17-lijepak-za-keramiku-25-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/191098.jpg",
    "image": "assets/products/ent-038.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 32,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CM 17",
      "Pakovanje": "25 kg",
      "Entext šifra": "191098"
    },
    "description": "CM 17 • 25 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "39",
    "sku": "ENT-039",
    "sourceSku": "191002",
    "name": "CERESIT CM 11 lijepak za keramiku 25 kg",
    "category": "Građevinski program",
    "brand": "CERESIT",
    "source": "https://entext.me/product/ceresit-cm-11-lijepak-za-keramiku-25-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/191002.jpg",
    "image": "assets/products/ent-039.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 18,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CM 11",
      "Pakovanje": "25 kg",
      "Entext šifra": "191002"
    },
    "description": "CM 11 • 25 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "40",
    "sku": "ENT-040",
    "sourceSku": "193216",
    "name": "CERESIT CM 16 lijepak za keramiku 5 kg",
    "category": "Građevinski program",
    "brand": "CERESIT",
    "source": "https://entext.me/product/ceresit-cm-16-lijepak-za-keramiku-5-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/193216.jpg",
    "image": "assets/products/ent-040.jpg",
    "imageKind": "photo",
    "photoNote": "Javna fotografija ovog modela može prikazivati drugo pakovanje; za količinu pogledajte naziv artikla.",
    "baseNet": 10,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CM 16",
      "Pakovanje": "5 kg",
      "Entext šifra": "193216"
    },
    "description": "CM 16 • 5 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "41",
    "sku": "ENT-041",
    "sourceSku": "194163",
    "name": "CERESIT CM 22 mega format flexible 20 kg",
    "category": "Građevinski program",
    "brand": "HENKEL SRBIJA d.o.o",
    "source": "https://entext.me/product/ceresit-cm-22-mega-format-flexible-20-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/194163.jpg",
    "image": "assets/products/ent-041.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 39,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CM 22",
      "Pakovanje": "20 kg",
      "Entext šifra": "194163"
    },
    "description": "CM 22 · 20 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "42",
    "sku": "ENT-042",
    "sourceSku": "194204",
    "name": "CERESIT CT 17 prajmer 2 l",
    "category": "Građevinski program",
    "brand": "CERESIT",
    "source": "https://entext.me/product/ceresit-ct-17-prajmer-2-l/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/194204.jpg",
    "image": "assets/products/ent-042.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 12,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CT 17",
      "Pakovanje": "2 l",
      "Entext šifra": "194204"
    },
    "description": "CT 17 • 2 l",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "43",
    "sku": "ENT-043",
    "sourceSku": "194281",
    "name": "CERESIT CM 49 fleksibilan lijepak klase S2, bijeli, 20 kg",
    "category": "Građevinski program",
    "brand": "CERESIT",
    "source": "https://entext.me/product/ceresit-cm-49-fleksibilan-lijepak-klase-s2-bijeli-20-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/194281.jpg",
    "image": "assets/products/ent-043.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 24,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CM 49",
      "Klasa": "S2",
      "Boja": "Bijela",
      "Pakovanje": "20 kg",
      "Entext šifra": "194281"
    },
    "description": "CM 49 • S2 • Bijela • 20 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "44",
    "sku": "ENT-044",
    "sourceSku": "192327",
    "name": "CERESIT CT 84 pur pjena za lijepljenje stiropora 850 ml",
    "category": "Građevinski program",
    "brand": "HENKEL SRBIJA d.o.o",
    "source": "https://entext.me/product/ceresit-ct-84-pur-pjena-za-lijepljenje-stiropora-850-ml/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/192327.jpg",
    "image": "assets/products/ent-044.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 32,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CT 84",
      "Pakovanje": "850 ml",
      "Entext šifra": "192327"
    },
    "description": "CT 84 • 850 ml",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "45",
    "sku": "ENT-045",
    "sourceSku": "194239",
    "name": "CERESIT CT 74 silikonski malter baza 1.5 mm 25 kg",
    "category": "Građevinski program",
    "brand": "HENKEL SRBIJA d.o.o",
    "source": "https://entext.me/product/ceresit-ct-74-silikonski-malter-baza-1-5-mm-25-kg/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/194239.jpg",
    "image": "assets/products/ent-045.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 18,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CT 74",
      "Granulacija": "1,5 mm",
      "Pakovanje": "25 kg",
      "Entext šifra": "194239"
    },
    "description": "CT 74 • 1,5 mm • 25 kg",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "46",
    "sku": "ENT-046",
    "sourceSku": "194279",
    "name": "CERESIT CE 89 dvokomponentna epoksidna fug masa i ljepilo 2.5kg toffi 844",
    "category": "Građevinski program",
    "brand": "HENKEL SRBIJA d.o.o",
    "source": "https://entext.me/product/ceresit-ce-89-dvokomponentna-epoksidna-fug-masa-i-ljepilo-2-5-kg-toffi/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/194279.jpg",
    "image": "assets/products/ent-046.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 10,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "CE 89",
      "Pakovanje": "2,5 kg",
      "Boja": "Toffi 844",
      "Entext šifra": "194279"
    },
    "description": "CE 89 • 2,5 kg • Toffi 844",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "47",
    "sku": "ENT-047",
    "sourceSku": "193051",
    "name": "CERESIT FT 101 siva zaptivna masa 280 ml",
    "category": "Građevinski program",
    "brand": "HENKEL SRBIJA d.o.o",
    "source": "https://entext.me/product/ceresit-ft-101-siva-zaptivna-masa-280-ml/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/193051.jpg",
    "image": "assets/products/ent-047.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 39,
    "unit": "pak.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "FT 101",
      "Pakovanje": "280 ml",
      "Boja": "Siva",
      "Entext šifra": "193051"
    },
    "description": "FT 101 • 280 ml • Siva",
    "fallback": "assets/products/fallback-materijali.svg"
  },
  {
    "id": "48",
    "sku": "ENT-048",
    "sourceSku": "",
    "name": "1362 Stolica sa rukonaslonom Star 24",
    "category": "Namještaj i dekoracija",
    "brand": "EMU",
    "source": "https://entext.me/product/1362-stolica-sa-rukonaslonom-star-24/",
    "remoteImage": "https://www.goodform.ch/media/catalog/product/1/3/1362-24.jpg",
    "image": "assets/products/ent-048.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 85,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Vrsta": "Stolica"
    },
    "description": "Stolica",
    "fallback": "assets/products/fallback-namjestaj.svg"
  },
  {
    "id": "49",
    "sku": "ENT-049",
    "sourceSku": "",
    "name": "1301 Stolica sa rukonaslonom Apero 24",
    "category": "Namještaj i dekoracija",
    "brand": "EMU",
    "source": "https://entext.me/product/1301-stolica-sa-rukonaslonom-apero-24/",
    "remoteImage": "https://media.s-bol.com/YngZVjMvNpJM/wQYjQ8/550x777.jpg",
    "image": "assets/products/ent-049.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 135,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Vrsta": "Stolica"
    },
    "description": "Stolica",
    "fallback": "assets/products/fallback-namjestaj.svg"
  },
  {
    "id": "50",
    "sku": "ENT-050",
    "sourceSku": "",
    "name": "208 Stolica Urban 23",
    "category": "Namještaj i dekoracija",
    "brand": "EMU",
    "source": "https://entext.me/product/208-stolica-urban-23/",
    "remoteImage": "https://cdn.mohd.it/cache/image/width%3D1200%2Cformat%3Dwebp/media/catalog/product/2/0/20823700x700.jpg",
    "image": "assets/products/ent-050.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 180,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Vrsta": "Stolica"
    },
    "description": "Stolica",
    "fallback": "assets/products/fallback-namjestaj.svg"
  },
  {
    "id": "51",
    "sku": "ENT-051",
    "sourceSku": "",
    "name": "314I12 Stolica Arc en Ciel White",
    "category": "Namještaj i dekoracija",
    "brand": "EMU",
    "source": "https://entext.me/product/314i12-stolica-arc-en-ciel-white/",
    "remoteImage": "https://comenido.it/cdn/shop/files/303142300A_1.jpg?v=1743010768&width=1024",
    "image": "assets/products/ent-051.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 64,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Vrsta": "Stolica"
    },
    "description": "Stolica",
    "fallback": "assets/products/fallback-namjestaj.svg"
  },
  {
    "id": "52",
    "sku": "ENT-052",
    "sourceSku": "",
    "name": "111 Stolica Ronda White",
    "category": "Namještaj i dekoracija",
    "brand": "EMU",
    "source": "https://entext.me/product/111-stolica-ronda-white/",
    "remoteImage": "https://www.einrichten-design.fr/media/c9/b3/c6/1679907039/Emu-Ronda-Stuhl-Outdoor-9.JPG",
    "image": "assets/products/ent-052.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 85,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Vrsta": "Stolica"
    },
    "description": "Stolica",
    "fallback": "assets/products/fallback-namjestaj.svg"
  },
  {
    "id": "53",
    "sku": "ENT-053",
    "sourceSku": "",
    "name": "639 Stolica Mom Dove Grey",
    "category": "Namještaj i dekoracija",
    "brand": "EMU",
    "source": "https://entext.me/product/639-stolica-mom-dove-grey/",
    "remoteImage": "https://www.miliashop.com/257816-home_default/mom-emu-chair.jpg",
    "image": "assets/products/ent-053.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 135,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Vrsta": "Stolica"
    },
    "description": "Stolica",
    "fallback": "assets/products/fallback-namjestaj.svg"
  },
  {
    "id": "54",
    "sku": "ENT-054",
    "sourceSku": "405044",
    "name": "GALA zidna lampa 1xG9, black",
    "category": "Namještaj i dekoracija",
    "brand": "Faro Barcelona",
    "source": "https://entext.me/product/gala-zidna-lampa-1xg9-black/",
    "remoteImage": "https://d7rh5s3nxmpy4.cloudfront.net/CMP4114/20/63506_R1.jpg",
    "image": "assets/products/ent-054.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 180,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Tip grla": "1 × G9",
      "Boja": "Crna",
      "Zaštita": "IP44",
      "Napon": "100–240 V",
      "Frekvencija": "50/60 Hz",
      "Entext šifra": "405044"
    },
    "description": "1 × G9 • Crna • IP44 • 100–240 V • 50/60 Hz",
    "fallback": "assets/products/fallback-namjestaj.svg"
  },
  {
    "id": "55",
    "sku": "ENT-055",
    "sourceSku": "361367",
    "name": "LOGIS 100 česma za lavabo sa piletom, chrome",
    "category": "Kupatilo",
    "brand": "HANSGROHE S E",
    "source": "https://entext.me/product/logis-100-cesma-za-lavabo-chrome/",
    "remoteImage": "https://www.entext.me/wp-content/uploads/2023/03/361367.jpg",
    "image": "assets/products/ent-055.jpg",
    "imageKind": "photo",
    "photoNote": "",
    "baseNet": 360,
    "unit": "kom.",
    "pack": 1,
    "boxCoverage": null,
    "attributes": {
      "Model": "LOGIS 100",
      "Završna obrada": "Chrome",
      "Vrsta": "Česma za lavabo sa piletom",
      "Entext šifra": "361367"
    },
    "description": "LOGIS 100 • Chrome • Česma za lavabo sa piletom",
    "fallback": "assets/products/fallback-kupatilo.svg"
  }
];
